modal:
  'Tab': select_next
  'Down': select_next
  'Backtab': select_prev
  'Up': select_prev
  'Enter': confirm
  'Escape': cancel

room_list:
  'Down': next_room
  'Up': prev_room
  'k': search_rooms
  'PageUp': scroll_up
  'PageDown': scroll_down
  'Escape': back
  'Tab': next_window
  'Enter': select_room
  'Ctrl+F': search_rooms
  's': settings

room:
  'Up': scroll_up
  'Down': scroll_down
  'PageUp': scroll_up_page
  'PageDown': scroll_down_page
  'Enter': send
  'Escape': back
  'Tab': next_window
  'Ctrl+U': toggle_user_list
